language: en-US
tone_instructions: 'Be a direct but constructive or angry Senior Developer'
early_access: false
enable_free_tier: true
auto_resolve_threads: true
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  poem: false
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: true
    base_branches: [main]
  finishing_touches:
    docstrings:
      enabled: true
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: false
    github-checks:
      enabled: true
      timeout_ms: 60000
    languagetool:
      enabled: true
      enabled_only: false
      level: default
    biome:
      enabled: true
    checkov:
      enabled: true
    semgrep:
      enabled: true
chat:
  auto_reply: true
  create_issues: false
knowledge_base:
  opt_out: true
code_generation:
  docstrings:
    language: en-US
