import os

REF_GENOME = "GRCh38"

PROGRAM_STORAGE_DIR = os.path.join(os.path.expanduser("~"), ".kath")
PROGRAM_STORAGE_DIR_SHARED = os.path.join(PROGRAM_STORAGE_DIR, "shared")
PROGRAM_STORAGE_DIR_SHARED_DATA = os.path.join(PROGRAM_STORAGE_DIR_SHARED, "data")
PROGRAM_STORAGE_DIR_SHARED_DATA_DISEASES = os.path.join(PROGRAM_STORAGE_DIR_SHARED_DATA, "diseases")
PROGRAM_STORAGE_DIR_SHARED_BLAST = os.path.join(PROGRAM_STORAGE_DIR_SHARED, "blast_results")
PROGRAM_STORAGE_DIR_SHARED_DATA_FASTA = os.path.join(PROGRAM_STORAGE_DIR_SHARED_DATA, "fasta_files")
PROGRAM_STORAGE_DIR_SHARED_DATA_FASTA_UPLOADS = os.path.join(
    PROGRAM_STORAGE_DIR_SHARED_DATA_FASTA,
    "uploads"
)
