import os
from pathlib import Path

REF_GENOME = "GRCh38"

PROGRAM_STORAGE_DIR = Path(os.path.join(os.path.expanduser("~"), ".kath"))
PROGRAM_STORAGE_DIR_SHARED = Path(os.path.join(PROGRAM_STORAGE_DIR, "shared"))
PROGRAM_STORAGE_DIR_SHARED_DATA = Path(os.path.join(PROGRAM_STORAGE_DIR_SHARED, "data"))
PROGRAM_STORAGE_DIR_SHARED_DATA_DISEASES = Path(
    os.path.join(PROGRAM_STORAGE_DIR_SHARED_DATA, "diseases")
)
PROGRAM_STORAGE_DIR_SHARED_BLAST = Path(
    os.path.join(PROGRAM_STORAGE_DIR_SHARED_DATA, "blast_results")
)
PROGRAM_STORAGE_DIR_SHARED_DATA_FASTA = Path(
    os.path.join(PROGRAM_STORAGE_DIR_SHARED_DATA, "fasta_files")
)
PROGRAM_STORAGE_DIR_SHARED_DATA_FASTA_SAMPLES = Path(
    os.path.join(PROGRAM_STORAGE_DIR_SHARED_DATA_FASTA, "samples")
)
PROGRAM_STORAGE_DIR_SHARED_DATA_FASTA_UPLOADS = Path(
    os.path.join(PROGRAM_STORAGE_DIR_SHARED_DATA_FASTA, "uploads")
)
PROGRAM_STORAGE_DIR_ENVIRONMENT = Path(os.path.join(PROGRAM_STORAGE_DIR, "environment"))
PROGRAM_STORAGE_DIR_PDFS = Path(os.path.join(PROGRAM_STORAGE_DIR, "pdfs"))
