name: Build for all platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Install dependencies
        run: |
            npm run init
            python -m venv .venv
            .venv\Scripts\pip install -r requirements.txt
      - name: Build for Windows
        run: npm run build
      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: ./dist

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          npm run init
          python -m venv .venv
          .venv/bin/pip install -r requirements.txt
      - name: Build for macOS
        run: npm run build
      - name: Upload macOS build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: ./dist

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          npm run init
          python -m venv .venv
          .venv/bin/pip install -r requirements.txt
      - name: Build for Linux
        run: npm run build
      - name: Upload Linux build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: ./dist

  download-artifacts:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
      - name: Download Windows build artifacts
        uses: actions/download-artifact@v2
        with:
          name: windows-build
          path: ./artifacts/windows
      - name: Download macOS build artifacts
        uses: actions/download-artifact@v2
        with:
          name: macos-build
          path: ./artifacts/macos
      - name: Download Linux build artifacts
        uses: actions/download-artifact@v2
        with:
          name: linux-build
          path: ./artifacts/linux
      - name: List downloaded files
        run: ls -R ./artifacts
