name: Build for all platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            name: windows
            venv_cmd: python -m venv .venv
            activate_cmd: .venv\\Scripts\\activate
          - os: ubuntu-latest
            name: linux
            venv_cmd: python3 -m venv .venv
            activate_cmd: source .venv/bin/activate
          - os: macos-latest
            name: macos
            venv_cmd: python3 -m venv .venv
            activate_cmd: source .venv/bin/activate
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node.js dependencies
        run: npm run init

      - name: Create and activate virtual environment
        run: |
          ${{ matrix.venv_cmd}}
          echo "Activating virtual environment..."
          ${{ matrix.activate_cmd }}
          pip install -r requirements.txt

      - name: Build for ${{ matrix.os }}
        run: npm run build

      - name: Upload ${{ matrix.os }} build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: ./dist
