name: Lint code

on:
  push:

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
  
    - name: Install Node.js dependencies
      run: |
        npm install
        cd frontend
        npm install

    - name: Analyzing the code with eslint
      run: npm run lint-action

  backend-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f ./backend/requirements.txt ]; then pip install -r ./backend/requirements.txt; fi
        if [ -f ./backend/requirements_dev.txt ]; then pip install -r ./backend/requirements_dev.txt; fi

    - name: Analyzing the code with pylint
      run: pylint --rcfile=./backend/.pylintrc --fail-under=10 --recursive=y --disable=fixme ./backend/src/